service: naa-server

# Enforce Serverless to read and load your local .env keys during compilation
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: dev

  environment:
    # Environment & Port Context
    NODE_ENV: ${env:NODE_ENV}
    PORT: ${env:PORT}

    # Core Database Layer
    MONGO_URI: ${env:MONGO_URI}

    # Authentication Security Tokens
    JWT_SECRET: ${env:JWT_SECRET}

    # Root Administrative Credentials
    ADMIN_EMAIL: ${env:ADMIN_EMAIL}
    ADMIN_PASSWORD: ${env:ADMIN_PASSWORD}

    # Institutional Cross-Origin Endpoints
    ADMIN_URL: ${env:ADMIN_URL}
    CLIENT_URL: ${env:CLIENT_URL}

    # Brevo Transactional SMTP Mail Infrastructure
    SMTP_SERVER: ${env:SMTP_SERVER}
    SMTP_PORT: ${env:SMTP_PORT}
    SMTP_LOGIN: ${env:SMTP_LOGIN}
    SMTP_KEY: ${env:SMTP_KEY}
    SENDER_EMAIL: ${env:SENDER_EMAIL}

    # Razorpay Operational Financial Gateways
    RAZORPAY_API_KEY: ${env:RAZORPAY_API_KEY}
    RAZORPAY_SECRET_KEY: ${env:RAZORPAY_SECRET_KEY}

    # Cloudinary Cloud Asset Management Bucket Pipeline
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    CLOUDINARY_API_SECRET: ${env:CLOUDINARY_API_SECRET}

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline

package:
  patterns:
    - '!.env' # Ensures the raw physical file is never bundled into your deployment zip package